avoid out of range enum cast in HostReg
In file included from /home/jan/Work/swanstation/src/core/bus.cpp:6:
In file included from /home/jan/Work/swanstation/src/core/cpu_code_cache.h:14:
/home/jan/Work/swanstation/src/core/cpu_recompiler_types.h:70:37: error: integer value 16 is outside the valid range of values [0, 15] for the enumeration type 'Code' [-Wenum-constexpr-conver
sion]
   70 | constexpr HostReg HostReg_Invalid = static_cast<HostReg>(HostReg_Count);
      |                                     ^
2 warnings and 1 error generated.

The code was unspecified behavior in C++ prior to C++17, and was changed
to undefined behavior in C++17. Recent versions of Clang have added a
warning that is treated as an error by default for it, and this commit
fixes compilation on recent Clang.

Ref: https://wiki.sei.cmu.edu/confluence/display/cplusplus/INT50-CPP.+Do+not+cast+to+an+out-of-range+enumeration+value
Ref: https://releases.llvm.org/18.1.4/tools/clang/docs/DiagnosticsReference.html#wenum-constexpr-conversion